rgbd_odometry:
  ros__parameters:
    frame_id: base_link
    odom_frame_id: odom
    publish_tf: true
    wait_for_transform: 0.2
    approx_sync: false
    sync_queue_size: 5
    qos_image: 2
    qos: 2
    qos_camera_info: 2
    qos_imu: 2
    subscribe_rgb: true
    subscribe_depth: true
    subscribe_imu: true
    always_process_most_recent_frame: true
    publish_null_when_lost: true
    Odom/Strategy: "0"
    Odom/ResetCountdown: "1"
    Odom/GuessMotion: "true"
    Vis/MinInliers: "15"
    Vis/FeatureType: "6"
    GFTT/MinDistance: "7"

rtabmap:
  ros__parameters:
    frame_id: base_link
    map_frame_id: map
    odom_frame_id: odom
    publish_tf: true
    wait_for_transform: 0.2
    approx_sync: false
    sync_queue_size: 10
    topic_queue_size: 10
    qos_image: 2
    qos_camera_info: 2
    qos_odom: 1
    qos_imu: 2
    subscribe_rgb: true
    subscribe_depth: true
    subscribe_odom_info: false
    subscribe_imu: true
    Reg/Strategy: "0"
    RGBD/NeighborLinkRefining: "true"
    RGBD/ProximityBySpace: "true"
    RGBD/OptimizeFromGraphEnd: "false"
    RGBD/AngularUpdate: "0.05"
    RGBD/LinearUpdate: "0.05"
    Rtabmap/DetectionRate: "10.0"
    Rtabmap/TimeThr: "90"
    Mem/IncrementalMemory: "true"
    Mem/InitWMWithAllNodes: "false"
    Grid/FromDepth: "true"
    Grid/3D: "true"
    Grid/RangeMax: "8.0"
    Grid/CellSize: "0.05"
