<?xml version="1.0"?>
<package format="3">
  <name>depth_bringup</name>
  <version>0.1.0</version>
  <description>Launch and configuration for Intel D456 RGB-D RTAB-Map mapping.</description>
  <maintainer email="hanlacar@users.noreply.github.com">hanlacar</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>rtabmap_odom</exec_depend>
  <exec_depend>rtabmap_slam</exec_depend>
  <exec_depend>rtabmap_viz</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>depth_description</exec_depend>
  <exec_depend>depth_monitor</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
