image_key_order:
  - isaac_ros.noble.ros2_jazzy.realsense.gr00t_workflow.ur_manipulation.franka_manipulation.mega_manipulation.nova_carter
context_overrides:
  isaac_ros: ..
  noble: ..
cache_to_registry_names: []
cache_from_registry_names:
  - local
remote_builder: {}
