#!/usr/bin/env python3
"""Build a ramp-preserving working copy of the two-lane RTAB-Map database.

The source databases are opened read-only. Only a copied seed database is
updated. RTAB-Map reprocess is run separately on that seed so node-local grids,
the optimized graph and the global occupancy are regenerated by RTAB-Map.
"""

from __future__ import annotations

import argparse
import json
import math
import shutil
import sqlite3
import struct
from pathlib import Path

import numpy as np
from scipy.signal import savgol_filter
from scipy.ndimage import gaussian_filter1d


ROOT = Path("/home/qor/depth_ws")
BASE_DB = ROOT / "maps/competition_338.db"
AUX_DB = ROOT / "maps/map_20260906_091640/rtabmap.db"
MERGED_DB = ROOT / "maps/merged_competition_1lane_2lane/rtabmap.db"
OUTPUT_DIR = ROOT / "maps/merged_competition_1lane_2lane_ramp"
SEED_DB = OUTPUT_DIR / "work/ramp_pose_seed.db"
REPORT = OUTPUT_DIR / "work/ramp_build_report.json"
FLAT_POSES = Path("/tmp/ramp_export/merged_flat_poses.txt")
BASE_OPT_POSES = Path("/tmp/rtabmap_audit_poses/competition_338_poses.txt")
AUX_OPT_POSES = Path("/tmp/rtabmap_audit_poses/map_091640_poses.txt")


ANCHOR_GROUPS = {
    "departure_rejoin": [(243, 5), (251, 21), (698, 285),
                         (772, 307), (812, 313)],
    "s_curve": [(1158, 447), (1168, 448), (1238, 481), (1248, 489),
                (1258, 493), (1268, 494), (1278, 496)],
    "right_angle_corner": [(1519, 589), (1559, 598),
                           (1609, 630), (1629, 641)],
    "crosswalk": [(2370, 919), (2401, 933), (2411, 936),
                  (2431, 943), (2441, 944), (2451, 952)],
    "final_return": [(2894, 1134), (2914, 1140), (2924, 1145)],
}


def matrix(blob: bytes) -> np.ndarray:
    result = np.eye(4)
    result[:3, :4] = np.asarray(struct.unpack("<12f", blob)).reshape(3, 4)
    return result


def pose_blob(pose: np.ndarray) -> bytes:
    return struct.pack("<12f", *pose[:3, :4].astype(np.float32).ravel())


def load_raw(path: Path):
    connection = sqlite3.connect(f"file:{path.resolve()}?mode=ro&immutable=1", uri=True)
    rows = list(connection.execute("SELECT id,stamp,pose FROM Node ORDER BY stamp,id"))
    connection.close()
    return {node_id: matrix(blob) for node_id, _, blob in rows}, {
        node_id: stamp for node_id, stamp, _ in rows}


def quaternion_yaw(x: float, y: float, z: float, w: float) -> float:
    return math.atan2(2*(w*z+x*y), 1-2*(y*y+z*z))


def load_exported(path: Path):
    poses = {}
    for line in path.read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        values = line.split()
        if len(values) != 9:
            continue
        node_id = int(values[8])
        x, y, z = map(float, values[1:4])
        qx, qy, qz, qw = map(float, values[4:8])
        poses[node_id] = (x, y, z, quaternion_yaw(qx, qy, qz, qw))
    return poses


def exported_matrices(path: Path):
    result = {}
    for node_id, (x, y, z, yaw) in load_exported(path).items():
        result[node_id] = compose_pose(x, y, z, yaw, 0.0)
    return result


def fit_se2(aux: dict[int, np.ndarray], base: dict[int, np.ndarray], pairs):
    source = np.asarray([aux[a][:2, 3] for a, _ in pairs])
    target = np.asarray([base[b][:2, 3] for _, b in pairs])
    sc, tc = source.mean(0), target.mean(0)
    s, t = source-sc, target-tc
    theta = math.atan2(np.sum(s[:, 0]*t[:, 1]-s[:, 1]*t[:, 0]),
                       np.sum(s*t))
    rotation = np.asarray([[math.cos(theta), -math.sin(theta)],
                           [math.sin(theta), math.cos(theta)]])
    translation = tc-sc@rotation.T
    residuals = np.linalg.norm(source@rotation.T+translation-target, axis=1)
    free_scale = float(np.sum(t*(s@rotation.T))/np.sum(s*s))
    return theta, translation, residuals, free_scale


def compose_pose(x: float, y: float, z: float, yaw: float, pitch: float) -> np.ndarray:
    cy, sy = math.cos(yaw), math.sin(yaw)
    cp, sp = math.cos(pitch), math.sin(pitch)
    rz = np.asarray([[cy, -sy, 0], [sy, cy, 0], [0, 0, 1.0]])
    ry = np.asarray([[cp, 0, sp], [0, 1.0, 0], [-sp, 0, cp]])
    result = np.eye(4)
    result[:3, :3] = rz@ry
    result[:3, 3] = (x, y, z)
    return result


def relative_profile(aux: dict[int, np.ndarray]):
    ids = np.arange(330, 651)
    observed_ids = np.asarray([i for i in sorted(aux) if 330 <= i <= 650])
    observed_z = np.asarray([aux[i][2, 3] for i in observed_ids])
    raw_z = np.interp(ids, observed_ids, observed_z)
    left = float(np.median([aux[i][2, 3] for i in range(345, 366) if i in aux]))
    right = float(np.median([aux[i][2, 3] for i in range(610, 631) if i in aux]))
    baseline = left+(right-left)*(ids-355)/(620-355)
    # A broad Gaussian suppresses frame-scale VSLAM Z noise. Enforce one
    # monotonic ascent and descent around the data-derived peak; this removes
    # non-physical pitch sign flips while retaining the measured envelope.
    height = np.maximum(gaussian_filter1d(raw_z-baseline, 8.0), 0.0)
    taper = np.ones_like(height)
    lo = ids < 365
    taper[lo] = np.clip((ids[lo]-345)/20, 0, 1)
    hi = ids > 600
    taper[hi] = np.clip((630-ids[hi])/30, 0, 1)
    height = np.maximum(height*taper, 0.0)
    height[ids <= 345] = 0.0
    height[ids >= 630] = 0.0
    peak_index = int(np.argmin(np.abs(ids-481)))
    ascent = np.maximum.accumulate(height[:peak_index+1])
    descent = np.maximum.accumulate(height[peak_index:][::-1])[::-1]
    peak = min(ascent[-1], descent[0])
    if ascent[-1] > 0: ascent *= peak/ascent[-1]
    if descent[0] > 0: descent *= peak/descent[0]
    height = np.r_[ascent[:-1], descent]
    return ids, height, {"left_baseline": left, "right_baseline": right,
                         "peak_m": float(height.max()),
                         "peak_node": int(ids[np.argmax(height)])}


def source_id_by_stamp(source_stamps, stamp):
    node_id, error = min(source_stamps.items(), key=lambda item: abs(item[1]-stamp))
    if abs(error-stamp) > 0.02:
        raise RuntimeError(f"no source timestamp match for {stamp}: nearest {error}")
    return node_id


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--replace-seed", action="store_true")
    args = parser.parse_args()
    for required in (FLAT_POSES, BASE_OPT_POSES, AUX_OPT_POSES):
        if not required.exists():
            raise FileNotFoundError(f"export optimized poses first: {required}")
    OUTPUT_DIR.joinpath("work").mkdir(parents=True, exist_ok=True)
    if SEED_DB.exists() and not args.replace_seed:
        raise FileExistsError(f"seed already exists: {SEED_DB}")
    if SEED_DB.exists():
        SEED_DB.unlink()

    base, base_stamps = load_raw(BASE_DB)
    aux, aux_stamps = load_raw(AUX_DB)
    base_opt = exported_matrices(BASE_OPT_POSES)
    aux_opt = exported_matrices(AUX_OPT_POSES)
    flat = load_exported(FLAT_POSES)
    fits = {}
    for name, pairs in ANCHOR_GROUPS.items():
        theta, translation, residuals, free_scale = fit_se2(aux_opt, base_opt, pairs)
        fits[name] = {
            "theta_deg": math.degrees(theta),
            "translation_m": translation.tolist(),
            "rms_m": float(np.sqrt(np.mean(residuals**2))),
            "median_m": float(np.median(residuals)),
            "max_m": float(residuals.max()),
            "free_scale_diagnostic_only": free_scale,
            "scale_applied": 1.0,
            "pairs": pairs,
            "residuals_m": residuals.tolist(),
        }

    global_pairs = [(772, 307), (1692, 639), (2441, 944),
                    (2894, 1134), (3258, 1254)]
    gtheta, gt, gres, gscale = fit_se2(aux_opt, base_opt, global_pairs)
    accepted_residuals = np.concatenate([
        np.asarray(fits[name]["residuals_m"]) for name in fits])
    height_ids, height_values, height_stats = relative_profile(aux)

    # The actual retained 091640 branch is 186-812. Use the robust departure +
    # rejoin fit. Distant submap fits are validation evidence that a single
    # global SE(2) is invalid, not transforms applied to absent duplicate data.
    applied = fits["departure_rejoin"]
    theta = math.radians(applied["theta_deg"])
    rotation = np.asarray([[math.cos(theta), -math.sin(theta)],
                           [math.sin(theta), math.cos(theta)]])
    translation = np.asarray(applied["translation_m"])

    shutil.copy2(MERGED_DB, SEED_DB)
    connection = sqlite3.connect(SEED_DB)
    rows = list(connection.execute("SELECT id,map_id,stamp FROM Node ORDER BY stamp,id"))
    desired = {}
    source_map = {}
    for node_id, map_id, stamp in rows:
        if map_id == 0:
            source_id = source_id_by_stamp(base_stamps, stamp)
            x, y, _, yaw = flat[node_id]
            aux_equivalent = float(np.interp(source_id,
                [115, 124, 157, 163, 200, 210],
                [345, 365, 470, 490, 600, 630]))
            z = float(np.interp(aux_equivalent, height_ids, height_values,
                                left=0.0, right=0.0)) if 115 <= source_id <= 210 else 0.0
        else:
            source_id = source_id_by_stamp(aux_stamps, stamp)
            source_opt = aux_opt[source_id]
            xy = source_opt[:2, 3]@rotation.T+translation
            x, y = map(float, xy)
            raw_yaw = math.atan2(source_opt[1, 0], source_opt[0, 0])
            yaw = raw_yaw+theta
            z = float(np.interp(source_id, height_ids, height_values,
                                left=0.0, right=0.0)) if 345 <= source_id <= 630 else 0.0
        desired[node_id] = [x, y, z, yaw, 0.0]
        source_map[node_id] = ["competition_338" if map_id == 0 else "091640", source_id]

    # Derive pitch from the corrected height profile along corrected XY arc
    # length. Positive height ahead means negative RTAB-Map Euler pitch.
    for map_id in (0, 1):
        ids = [node_id for node_id, mid, _ in rows if mid == map_id]
        for index, node_id in enumerate(ids):
            lo, hi = max(0, index-2), min(len(ids)-1, index+2)
            if hi == lo:
                pitch = 0.0
            else:
                a, b = desired[ids[lo]], desired[ids[hi]]
                ds = math.hypot(b[0]-a[0], b[1]-a[1])
                pitch = -math.atan2(b[2]-a[2], ds) if ds > 0.05 else 0.0
            desired[node_id][4] = pitch

    for node_id, values in desired.items():
        pose = compose_pose(*values)
        connection.execute("UPDATE Node SET pose=?,ground_truth_pose=? WHERE id=?",
                           (pose_blob(pose), pose_blob(pose), node_id))
    link_rows = list(connection.execute("SELECT rowid,from_id,to_id FROM Link"))
    for rowid, from_id, to_id in link_rows:
        transform = np.linalg.inv(compose_pose(*desired[from_id]))@compose_pose(*desired[to_id])
        connection.execute("UPDATE Link SET transform=? WHERE rowid=?",
                           (pose_blob(transform), rowid))
    # The old global visual edge is tied to the flat-map replay and RTAB-Map
    # republishes it one frame early (1304 -> 1303). Keep only the three
    # independently verified local-space cross-session constraints.
    removed_global_links = connection.execute(
        "DELETE FROM Link WHERE type=1 AND ((from_id<1291 AND to_id>=1291) "
        "OR (to_id<1291 AND from_id>=1291))").rowcount
    # Stale flat-map products must never be mistaken for regenerated results.
    connection.execute("UPDATE Admin SET opt_cloud=NULL,opt_ids=NULL,opt_poses=NULL,"
                       "opt_last_localization=NULL,opt_polygons_size=NULL,opt_polygons=NULL,"
                       "opt_tex_coords=NULL,opt_tex_materials=NULL,opt_map=NULL,"
                       "opt_map_x_min=NULL,opt_map_y_min=NULL,opt_map_resolution=NULL")
    connection.execute("UPDATE Data SET ground_cells=NULL,obstacle_cells=NULL,empty_cells=NULL")
    connection.commit()
    integrity = connection.execute("PRAGMA integrity_check").fetchone()[0]
    connection.close()

    report = {
        "source_files_untouched": [str(BASE_DB), str(AUX_DB), str(MERGED_DB)],
        "seed": str(SEED_DB), "seed_integrity": integrity,
        "global_se2_rejected": {
            "theta_deg": math.degrees(gtheta), "translation_m": gt.tolist(),
            "rms_m": float(np.sqrt(np.mean(gres**2))),
            "residuals_m": gres.tolist(), "free_scale": gscale,
            "scale_applied": 1.0,
        },
        "piecewise_validation_fits": fits,
        "accepted_anchor_rms_m": float(np.sqrt(np.mean(accepted_residuals**2))),
        "applied_to_retained_091640": applied,
        "height_profile": height_stats,
        "ramp_ranges_original_ids": {
            "competition_338": {"transition_and_ramp": [115, 210],
                                "uphill": [124, 157], "crest": [157, 163],
                                "downhill": [163, 200]},
            "091640": {"transition_and_ramp": [345, 630],
                       "uphill": [365, 470], "crest": [470, 490],
                       "downhill": [490, 600]},
        },
        "node_source_map": source_map,
        "removed_stale_global_cross_link_rows": removed_global_links,
    }
    REPORT.write_text(json.dumps(report, indent=2)+"\n")
    print(json.dumps({k: report[k] for k in (
        "seed", "seed_integrity", "global_se2_rejected",
        "accepted_anchor_rms_m", "applied_to_retained_091640",
        "height_profile", "ramp_ranges_original_ids")}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
